version: '3'
services:
  shu-room-use-crawler:
    image: shu-room-use-crawler
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "33030:9000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - CHROMIUM_PATH=/usr/bin/google-chrome
    working_dir: /app
    platform: linux/amd64